sudo: required

language: python

services:
  - docker

before_install:
- docker image pull iquod/autoqc:1.0-rc5

script:
- docker container run -v $PWD:/AutoQC_latest iquod/autoqc:1.0-rc5 bash -c "cp /AutoQC/data/* /AutoQC_latest/data/.; cd /AutoQC_latest; /usr/local/bin/nosetests tests/*.py"
