language: python
python:
  - "2.7"
# Setup anaconda
before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION Shapely netCDF4 matplotlib numpy scipy scikit-learn
install:
  - sudo apt-get install libhdf5-serial-dev libnetcdf-dev
  - conda install -y -c https://conda.binstar.org/jjhelmus pyproj
  - pip install wodpy
before_script:
# download auxiliary data
  - cd data; curl -O http://www.metoffice.gov.uk/hadobs/en4/data/EN_bgcheck_info.nc; cd ..;
script: nosetests tests/*.py