sudo: required

language: python

services:
  - docker

before_install:
- docker image pull iquod/autoqc:ubuntu-16.04

script:
- docker container run -v $PWD:/AutoQC_latest iquod/autoqc:ubuntu-16.04-patch-190606 bash -c "cp /AutoQC/data/* /AutoQC_latest/data/.; cd /AutoQC_latest; /usr/local/bin/nosetests tests/*.py"
