sudo: required

language: python

services:
  - docker

before_install:
- docker pull billmills/autoqc
- docker run billmills/autoqc /bin/bash -c "cd /AutoQC; git pull origin master; nosetests tests/*.py"

script:
- nosetests tests/*.py