sudo: required

language: python

services:
  - docker

before_install:
- docker pull iquod/autoqc

script:
- docker run -v $(pwd)/AutoQC:/AutoQC_latest iquod/autoqc /bin/bash -c "cp /AutoQC/data/* /AutoQC_latest/data/*; cd /AutoQC_latest; nosetests tests/*.py"
